"use client";

import { useEffect } from "react";
import { DM_Sans } from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";
import SSRProvider from "react-bootstrap/SSRProvider";
import { ReduxProvider } from "@/redux/provider";

import MainNavbar from "./MainNavbar";
import MainFooter from "./MainFooter";
import "./custom.css";

const fonts = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Pcari Movie App",
  description: "Generated by Fiz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-custom">
      <body className={fonts.className}>
        <ReduxProvider>
          {/* <SSRProvider> */}
            <MainNavbar />
            {children}
            <MainFooter />
          {/* </SSRProvider> */}
        </ReduxProvider>
      </body>
    </html>
  );
}
